version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: board-app-test-db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: board-app-test
    volumes:
      - mongo-test-data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  app-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: board-app-test
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      NODE_ENV: test
      MONGODB_URI: mongodb://mongodb:27017/board-app-test
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run test:coverage

  e2e-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: board-app-e2e
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      NODE_ENV: test
      MONGODB_URI: mongodb://mongodb:27017/board-app-test
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run test:e2e

volumes:
  mongo-test-data: